name: hacker_news
description: Hacker news app with BLOC pattern
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  thought_design_system:
    git:
      url: git://github.com/DeepThought-org/ThoughtDesignSystem-Flutter.git

  get_it: ^7.1.3

  flutter_bloc: ^7.0.0

  equatable: ^2.0.0

  http: ^0.13.3
  json_annotation: ^4.0.1

  beamer: ^0.14.0

  firebase_crashlytics: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.3
  json_serializable: ^4.1.2
  bloc_test: ^8.0.0

flutter:
  uses-material-design: true